import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Script from "next/script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/* Auto height postMessage to parent page for iframe resizing */}
        <Script id="iframe-height-post" strategy="afterInteractive">
          {`
            let resizeTimeout;
            function sendHeight() {
              clearTimeout(resizeTimeout);
              resizeTimeout = setTimeout(() => {
                const height = document.documentElement.scrollHeight;
                window.parent.postMessage({ iframeHeight: height }, "*");
              }, 100);
            }

            // Send on initial load and resize
            window.addEventListener("load", sendHeight);
            window.addEventListener("resize", sendHeight);

            // Observe changes in DOM that might affect height
            const observer = new MutationObserver(sendHeight);
            observer.observe(document.body, {
              childList: true,
              subtree: true,
              attributes: true,
              characterData: true
            });

            // Initial send
            sendHeight();
          `}
        </Script>

        {children}
      </body>
    </html>
  );
}
